# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pedido_pb2 as pedido__pb2


class GestionPedidosStub(object):
    """Servicio para gestionar pedidos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RealizarCompra = channel.unary_unary(
                '/pedidos.GestionPedidos/RealizarCompra',
                request_serializer=pedido__pb2.Compra.SerializeToString,
                response_deserializer=pedido__pb2.Respuesta.FromString,
                )


class GestionPedidosServicer(object):
    """Servicio para gestionar pedidos
    """

    def RealizarCompra(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GestionPedidosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RealizarCompra': grpc.unary_unary_rpc_method_handler(
                    servicer.RealizarCompra,
                    request_deserializer=pedido__pb2.Compra.FromString,
                    response_serializer=pedido__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pedidos.GestionPedidos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GestionPedidos(object):
    """Servicio para gestionar pedidos
    """

    @staticmethod
    def RealizarCompra(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pedidos.GestionPedidos/RealizarCompra',
            pedido__pb2.Compra.SerializeToString,
            pedido__pb2.Respuesta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
