# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pedido.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pedido.proto',
  package='pedidos',
  syntax='proto3',
  serialized_pb=_b('\n\x0cpedido.proto\x12\x07pedidos\"\xaa\x01\n\x06\x43ompra\x12\x0f\n\x07\x63liente\x18\x01 \x01(\t\x12\x10\n\x08producto\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x02\x12\x15\n\rpasarela_pago\x18\x04 \x01(\t\x12\x15\n\rmarca_tarjeta\x18\x05 \x01(\t\x12\r\n\x05\x62\x61nco\x18\x06 \x01(\t\x12\x0e\n\x06\x63omuna\x18\x07 \x01(\t\x12\x11\n\tdireccion\x18\x08 \x01(\t\x12\r\n\x05\x65mail\x18\t \x01(\t\"+\n\tRespuesta\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\r\n\x05\x65xito\x18\x02 \x01(\x08\x32I\n\x0eGestionPedidos\x12\x37\n\x0eRealizarCompra\x12\x0f.pedidos.Compra\x1a\x12.pedidos.Respuesta\"\x00\x62\x06proto3')
)




_COMPRA = _descriptor.Descriptor(
  name='Compra',
  full_name='pedidos.Compra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cliente', full_name='pedidos.Compra.cliente', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='producto', full_name='pedidos.Compra.producto', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='precio', full_name='pedidos.Compra.precio', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pasarela_pago', full_name='pedidos.Compra.pasarela_pago', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marca_tarjeta', full_name='pedidos.Compra.marca_tarjeta', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='banco', full_name='pedidos.Compra.banco', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comuna', full_name='pedidos.Compra.comuna', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direccion', full_name='pedidos.Compra.direccion', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='pedidos.Compra.email', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=196,
)


_RESPUESTA = _descriptor.Descriptor(
  name='Respuesta',
  full_name='pedidos.Respuesta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='pedidos.Respuesta.mensaje', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exito', full_name='pedidos.Respuesta.exito', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=241,
)

DESCRIPTOR.message_types_by_name['Compra'] = _COMPRA
DESCRIPTOR.message_types_by_name['Respuesta'] = _RESPUESTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Compra = _reflection.GeneratedProtocolMessageType('Compra', (_message.Message,), dict(
  DESCRIPTOR = _COMPRA,
  __module__ = 'pedido_pb2'
  # @@protoc_insertion_point(class_scope:pedidos.Compra)
  ))
_sym_db.RegisterMessage(Compra)

Respuesta = _reflection.GeneratedProtocolMessageType('Respuesta', (_message.Message,), dict(
  DESCRIPTOR = _RESPUESTA,
  __module__ = 'pedido_pb2'
  # @@protoc_insertion_point(class_scope:pedidos.Respuesta)
  ))
_sym_db.RegisterMessage(Respuesta)



_GESTIONPEDIDOS = _descriptor.ServiceDescriptor(
  name='GestionPedidos',
  full_name='pedidos.GestionPedidos',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=243,
  serialized_end=316,
  methods=[
  _descriptor.MethodDescriptor(
    name='RealizarCompra',
    full_name='pedidos.GestionPedidos.RealizarCompra',
    index=0,
    containing_service=None,
    input_type=_COMPRA,
    output_type=_RESPUESTA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GESTIONPEDIDOS)

DESCRIPTOR.services_by_name['GestionPedidos'] = _GESTIONPEDIDOS

# @@protoc_insertion_point(module_scope)
